FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish /src/src/Startup/MUnique.OpenMU.Startup.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine
WORKDIR /app
COPY --from=build /out ./
RUN apk add --no-cache krb5-libs
ENTRYPOINT ["dotnet", "MUnique.OpenMU.Startup.dll"]