FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
RUN apt-get update && apt-get install -y --no-install-recommends git
WORKDIR /src
RUN git clone --depth 1 https://github.com/MUnique/OpenMU.git .
RUN ls /src/src
COPY plugins/StatAliases/Aliases.cs /src/src/GameLogic/StatAliases.cs
RUN dotnet publish /src/src/Startup/MUnique.OpenMU.Startup.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine
WORKDIR /app
COPY --from=build /out ./
RUN apk add --no-cache krb5-libs
ENTRYPOINT ["dotnet", "MUnique.OpenMU.Startup.dll"]