// <copyright file="MapsterConfigurator.Generated.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by a roslyn code generator.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace MUnique.OpenMU.Persistence.EntityFramework.Model;

using MUnique.OpenMU.Persistence;
using Mapster;

/// <summary>
/// Configures Mapster to properly map these classes to the Persistence.BasicModel.
/// </summary>
public static class MapsterConfigurator
{
    private static bool isConfigured;

    /// <summary>
    /// Ensures that Mapster is configured to properly map these EF-Core persistence classes to the Persistence.BasicModel.
    /// </summary>
    public static void EnsureConfigured()
    {
        if (isConfigured)
        {
            return;
        }

        Mapster.TypeAdapterConfig.GlobalSettings.Default.PreserveReference(true);
        Mapster.TypeAdapterConfig.GlobalSettings.Default.IgnoreMember((member, side) => member.Name.StartsWith("Raw"));

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Statistics.MiniGameRankingEntry, MUnique.OpenMU.DataModel.Statistics.MiniGameRankingEntry>()
            .Include<MUnique.OpenMU.DataModel.Statistics.MiniGameRankingEntry, BasicModel.MiniGameRankingEntry>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.Account, MUnique.OpenMU.DataModel.Entities.Account>()
            .Include<MUnique.OpenMU.DataModel.Entities.Account, BasicModel.Account>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.AccountVip, MUnique.OpenMU.DataModel.Entities.AccountVip>()
            .Include<MUnique.OpenMU.DataModel.Entities.AccountVip, BasicModel.AccountVip>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.AppearanceData, MUnique.OpenMU.DataModel.Entities.AppearanceData>()
            .Include<MUnique.OpenMU.DataModel.Entities.AppearanceData, BasicModel.AppearanceData>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.Character, MUnique.OpenMU.DataModel.Entities.Character>()
            .Include<MUnique.OpenMU.DataModel.Entities.Character, BasicModel.Character>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.CharacterQuestState, MUnique.OpenMU.DataModel.Entities.CharacterQuestState>()
            .Include<MUnique.OpenMU.DataModel.Entities.CharacterQuestState, BasicModel.CharacterQuestState>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.Guild, MUnique.OpenMU.DataModel.Entities.Guild>()
            .Include<MUnique.OpenMU.DataModel.Entities.Guild, BasicModel.Guild>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.GuildMember, MUnique.OpenMU.DataModel.Entities.GuildMember>()
            .Include<MUnique.OpenMU.DataModel.Entities.GuildMember, BasicModel.GuildMember>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.Item, MUnique.OpenMU.DataModel.Entities.Item>()
            .Include<MUnique.OpenMU.DataModel.Entities.Item, BasicModel.Item>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.ItemAppearance, MUnique.OpenMU.DataModel.Entities.ItemAppearance>()
            .Include<MUnique.OpenMU.DataModel.Entities.ItemAppearance, BasicModel.ItemAppearance>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.ItemOptionLink, MUnique.OpenMU.DataModel.Entities.ItemOptionLink>()
            .Include<MUnique.OpenMU.DataModel.Entities.ItemOptionLink, BasicModel.ItemOptionLink>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.ItemStorage, MUnique.OpenMU.DataModel.Entities.ItemStorage>()
            .Include<MUnique.OpenMU.DataModel.Entities.ItemStorage, BasicModel.ItemStorage>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.LetterBody, MUnique.OpenMU.DataModel.Entities.LetterBody>()
            .Include<MUnique.OpenMU.DataModel.Entities.LetterBody, BasicModel.LetterBody>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.QuestMonsterKillRequirementState, MUnique.OpenMU.DataModel.Entities.QuestMonsterKillRequirementState>()
            .Include<MUnique.OpenMU.DataModel.Entities.QuestMonsterKillRequirementState, BasicModel.QuestMonsterKillRequirementState>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.SkillEntry, MUnique.OpenMU.DataModel.Entities.SkillEntry>()
            .Include<MUnique.OpenMU.DataModel.Entities.SkillEntry, BasicModel.SkillEntry>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.VipHistory, MUnique.OpenMU.DataModel.Entities.VipHistory>()
            .Include<MUnique.OpenMU.DataModel.Entities.VipHistory, BasicModel.VipHistory>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.VipPlan, MUnique.OpenMU.DataModel.Entities.VipPlan>()
            .Include<MUnique.OpenMU.DataModel.Entities.VipPlan, BasicModel.VipPlan>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.WCoinTransaction, MUnique.OpenMU.DataModel.Entities.WCoinTransaction>()
            .Include<MUnique.OpenMU.DataModel.Entities.WCoinTransaction, BasicModel.WCoinTransaction>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Entities.WCoinWallet, MUnique.OpenMU.DataModel.Entities.WCoinWallet>()
            .Include<MUnique.OpenMU.DataModel.Entities.WCoinWallet, BasicModel.WCoinWallet>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.AreaSkillSettings, MUnique.OpenMU.DataModel.Configuration.AreaSkillSettings>()
            .Include<MUnique.OpenMU.DataModel.Configuration.AreaSkillSettings, BasicModel.AreaSkillSettings>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.BattleZoneDefinition, MUnique.OpenMU.DataModel.Configuration.BattleZoneDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.BattleZoneDefinition, BasicModel.BattleZoneDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.CharacterClass, MUnique.OpenMU.DataModel.Configuration.CharacterClass>()
            .Include<MUnique.OpenMU.DataModel.Configuration.CharacterClass, BasicModel.CharacterClass>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.ChatServerDefinition, MUnique.OpenMU.DataModel.Configuration.ChatServerDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.ChatServerDefinition, BasicModel.ChatServerDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.ChatServerEndpoint, MUnique.OpenMU.DataModel.Configuration.ChatServerEndpoint>()
            .Include<MUnique.OpenMU.DataModel.Configuration.ChatServerEndpoint, BasicModel.ChatServerEndpoint>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.ConfigurationUpdate, MUnique.OpenMU.DataModel.Configuration.ConfigurationUpdate>()
            .Include<MUnique.OpenMU.DataModel.Configuration.ConfigurationUpdate, BasicModel.ConfigurationUpdate>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.ConfigurationUpdateState, MUnique.OpenMU.DataModel.Configuration.ConfigurationUpdateState>()
            .Include<MUnique.OpenMU.DataModel.Configuration.ConfigurationUpdateState, BasicModel.ConfigurationUpdateState>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition, MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition, BasicModel.ConnectServerDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.DropItemGroup, MUnique.OpenMU.DataModel.Configuration.DropItemGroup>()
            .Include<MUnique.OpenMU.DataModel.Configuration.DropItemGroup, BasicModel.DropItemGroup>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.DuelArea, MUnique.OpenMU.DataModel.Configuration.DuelArea>()
            .Include<MUnique.OpenMU.DataModel.Configuration.DuelArea, BasicModel.DuelArea>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.DuelConfiguration, MUnique.OpenMU.DataModel.Configuration.DuelConfiguration>()
            .Include<MUnique.OpenMU.DataModel.Configuration.DuelConfiguration, BasicModel.DuelConfiguration>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.EnterGate, MUnique.OpenMU.DataModel.Configuration.EnterGate>()
            .Include<MUnique.OpenMU.DataModel.Configuration.EnterGate, BasicModel.EnterGate>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.ExitGate, MUnique.OpenMU.DataModel.Configuration.ExitGate>()
            .Include<MUnique.OpenMU.DataModel.Configuration.ExitGate, BasicModel.ExitGate>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.GameClientDefinition, MUnique.OpenMU.DataModel.Configuration.GameClientDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.GameClientDefinition, BasicModel.GameClientDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.GameConfiguration, MUnique.OpenMU.DataModel.Configuration.GameConfiguration>()
            .Include<MUnique.OpenMU.DataModel.Configuration.GameConfiguration, BasicModel.GameConfiguration>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.GameMapDefinition, MUnique.OpenMU.DataModel.Configuration.GameMapDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.GameMapDefinition, BasicModel.GameMapDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.GameServerConfiguration, MUnique.OpenMU.DataModel.Configuration.GameServerConfiguration>()
            .Include<MUnique.OpenMU.DataModel.Configuration.GameServerConfiguration, BasicModel.GameServerConfiguration>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.GameServerDefinition, MUnique.OpenMU.DataModel.Configuration.GameServerDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.GameServerDefinition, BasicModel.GameServerDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.GameServerEndpoint, MUnique.OpenMU.DataModel.Configuration.GameServerEndpoint>()
            .Include<MUnique.OpenMU.DataModel.Configuration.GameServerEndpoint, BasicModel.GameServerEndpoint>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Gate, MUnique.OpenMU.DataModel.Configuration.Gate>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Gate, BasicModel.Gate>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.ItemDropItemGroup, MUnique.OpenMU.DataModel.Configuration.ItemDropItemGroup>()
            .Include<MUnique.OpenMU.DataModel.Configuration.ItemDropItemGroup, BasicModel.ItemDropItemGroup>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.JewelMix, MUnique.OpenMU.DataModel.Configuration.JewelMix>()
            .Include<MUnique.OpenMU.DataModel.Configuration.JewelMix, BasicModel.JewelMix>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.LevelDependentDamage, MUnique.OpenMU.DataModel.Configuration.LevelDependentDamage>()
            .Include<MUnique.OpenMU.DataModel.Configuration.LevelDependentDamage, BasicModel.LevelDependentDamage>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.MagicEffectDefinition, MUnique.OpenMU.DataModel.Configuration.MagicEffectDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.MagicEffectDefinition, BasicModel.MagicEffectDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.MasterSkillDefinition, MUnique.OpenMU.DataModel.Configuration.MasterSkillDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.MasterSkillDefinition, BasicModel.MasterSkillDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.MasterSkillRoot, MUnique.OpenMU.DataModel.Configuration.MasterSkillRoot>()
            .Include<MUnique.OpenMU.DataModel.Configuration.MasterSkillRoot, BasicModel.MasterSkillRoot>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.MiniGameChangeEvent, MUnique.OpenMU.DataModel.Configuration.MiniGameChangeEvent>()
            .Include<MUnique.OpenMU.DataModel.Configuration.MiniGameChangeEvent, BasicModel.MiniGameChangeEvent>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.MiniGameDefinition, MUnique.OpenMU.DataModel.Configuration.MiniGameDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.MiniGameDefinition, BasicModel.MiniGameDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.MiniGameReward, MUnique.OpenMU.DataModel.Configuration.MiniGameReward>()
            .Include<MUnique.OpenMU.DataModel.Configuration.MiniGameReward, BasicModel.MiniGameReward>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.MiniGameSpawnWave, MUnique.OpenMU.DataModel.Configuration.MiniGameSpawnWave>()
            .Include<MUnique.OpenMU.DataModel.Configuration.MiniGameSpawnWave, BasicModel.MiniGameSpawnWave>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.MiniGameTerrainChange, MUnique.OpenMU.DataModel.Configuration.MiniGameTerrainChange>()
            .Include<MUnique.OpenMU.DataModel.Configuration.MiniGameTerrainChange, BasicModel.MiniGameTerrainChange>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.MonsterAttribute, MUnique.OpenMU.DataModel.Configuration.MonsterAttribute>()
            .Include<MUnique.OpenMU.DataModel.Configuration.MonsterAttribute, BasicModel.MonsterAttribute>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.MonsterDefinition, MUnique.OpenMU.DataModel.Configuration.MonsterDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.MonsterDefinition, BasicModel.MonsterDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.MonsterSpawnArea, MUnique.OpenMU.DataModel.Configuration.MonsterSpawnArea>()
            .Include<MUnique.OpenMU.DataModel.Configuration.MonsterSpawnArea, BasicModel.MonsterSpawnArea>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Rectangle, MUnique.OpenMU.DataModel.Configuration.Rectangle>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Rectangle, BasicModel.Rectangle>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Skill, MUnique.OpenMU.DataModel.Configuration.Skill>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Skill, BasicModel.Skill>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.SkillComboDefinition, MUnique.OpenMU.DataModel.Configuration.SkillComboDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.SkillComboDefinition, BasicModel.SkillComboDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.SkillComboStep, MUnique.OpenMU.DataModel.Configuration.SkillComboStep>()
            .Include<MUnique.OpenMU.DataModel.Configuration.SkillComboStep, BasicModel.SkillComboStep>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.StatAttributeDefinition, MUnique.OpenMU.DataModel.Configuration.StatAttributeDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.StatAttributeDefinition, BasicModel.StatAttributeDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.SystemConfiguration, MUnique.OpenMU.DataModel.Configuration.SystemConfiguration>()
            .Include<MUnique.OpenMU.DataModel.Configuration.SystemConfiguration, BasicModel.SystemConfiguration>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.WarpInfo, MUnique.OpenMU.DataModel.Configuration.WarpInfo>()
            .Include<MUnique.OpenMU.DataModel.Configuration.WarpInfo, BasicModel.WarpInfo>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Quests.QuestDefinition, MUnique.OpenMU.DataModel.Configuration.Quests.QuestDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Quests.QuestDefinition, BasicModel.QuestDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Quests.QuestItemRequirement, MUnique.OpenMU.DataModel.Configuration.Quests.QuestItemRequirement>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Quests.QuestItemRequirement, BasicModel.QuestItemRequirement>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Quests.QuestMonsterKillRequirement, MUnique.OpenMU.DataModel.Configuration.Quests.QuestMonsterKillRequirement>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Quests.QuestMonsterKillRequirement, BasicModel.QuestMonsterKillRequirement>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Quests.QuestReward, MUnique.OpenMU.DataModel.Configuration.Quests.QuestReward>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Quests.QuestReward, BasicModel.QuestReward>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.AttributeRequirement, MUnique.OpenMU.DataModel.Configuration.Items.AttributeRequirement>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.AttributeRequirement, BasicModel.AttributeRequirement>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.CombinationBonusRequirement, MUnique.OpenMU.DataModel.Configuration.Items.CombinationBonusRequirement>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.CombinationBonusRequirement, BasicModel.CombinationBonusRequirement>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.IncreasableItemOption, MUnique.OpenMU.DataModel.Configuration.Items.IncreasableItemOption>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.IncreasableItemOption, BasicModel.IncreasableItemOption>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.ItemBasePowerUpDefinition, MUnique.OpenMU.DataModel.Configuration.Items.ItemBasePowerUpDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.ItemBasePowerUpDefinition, BasicModel.ItemBasePowerUpDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.ItemDefinition, MUnique.OpenMU.DataModel.Configuration.Items.ItemDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.ItemDefinition, BasicModel.ItemDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.ItemLevelBonusTable, MUnique.OpenMU.DataModel.Configuration.Items.ItemLevelBonusTable>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.ItemLevelBonusTable, BasicModel.ItemLevelBonusTable>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.ItemOfItemSet, MUnique.OpenMU.DataModel.Configuration.Items.ItemOfItemSet>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.ItemOfItemSet, BasicModel.ItemOfItemSet>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.ItemOption, MUnique.OpenMU.DataModel.Configuration.Items.ItemOption>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.ItemOption, BasicModel.ItemOption>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.ItemOptionCombinationBonus, MUnique.OpenMU.DataModel.Configuration.Items.ItemOptionCombinationBonus>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.ItemOptionCombinationBonus, BasicModel.ItemOptionCombinationBonus>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.ItemOptionDefinition, MUnique.OpenMU.DataModel.Configuration.Items.ItemOptionDefinition>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.ItemOptionDefinition, BasicModel.ItemOptionDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.ItemOptionOfLevel, MUnique.OpenMU.DataModel.Configuration.Items.ItemOptionOfLevel>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.ItemOptionOfLevel, BasicModel.ItemOptionOfLevel>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.ItemOptionType, MUnique.OpenMU.DataModel.Configuration.Items.ItemOptionType>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.ItemOptionType, BasicModel.ItemOptionType>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.ItemSetGroup, MUnique.OpenMU.DataModel.Configuration.Items.ItemSetGroup>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.ItemSetGroup, BasicModel.ItemSetGroup>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.ItemSlotType, MUnique.OpenMU.DataModel.Configuration.Items.ItemSlotType>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.ItemSlotType, BasicModel.ItemSlotType>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.Items.LevelBonus, MUnique.OpenMU.DataModel.Configuration.Items.LevelBonus>()
            .Include<MUnique.OpenMU.DataModel.Configuration.Items.LevelBonus, BasicModel.LevelBonus>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.ItemCrafting.ItemCrafting, MUnique.OpenMU.DataModel.Configuration.ItemCrafting.ItemCrafting>()
            .Include<MUnique.OpenMU.DataModel.Configuration.ItemCrafting.ItemCrafting, BasicModel.ItemCrafting>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.ItemCrafting.ItemCraftingRequiredItem, MUnique.OpenMU.DataModel.Configuration.ItemCrafting.ItemCraftingRequiredItem>()
            .Include<MUnique.OpenMU.DataModel.Configuration.ItemCrafting.ItemCraftingRequiredItem, BasicModel.ItemCraftingRequiredItem>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.ItemCrafting.ItemCraftingResultItem, MUnique.OpenMU.DataModel.Configuration.ItemCrafting.ItemCraftingResultItem>()
            .Include<MUnique.OpenMU.DataModel.Configuration.ItemCrafting.ItemCraftingResultItem, BasicModel.ItemCraftingResultItem>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings, MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings>()
            .Include<MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings, BasicModel.SimpleCraftingSettings>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Attributes.PowerUpDefinition, MUnique.OpenMU.DataModel.Attributes.PowerUpDefinition>()
            .Include<MUnique.OpenMU.DataModel.Attributes.PowerUpDefinition, BasicModel.PowerUpDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.DataModel.Attributes.PowerUpDefinitionValue, MUnique.OpenMU.DataModel.Attributes.PowerUpDefinitionValue>()
            .Include<MUnique.OpenMU.DataModel.Attributes.PowerUpDefinitionValue, BasicModel.PowerUpDefinitionValue>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.AttributeSystem.AttributeDefinition, MUnique.OpenMU.AttributeSystem.AttributeDefinition>()
            .Include<MUnique.OpenMU.AttributeSystem.AttributeDefinition, BasicModel.AttributeDefinition>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.AttributeSystem.StatAttribute, MUnique.OpenMU.AttributeSystem.StatAttribute>()
            .Include<MUnique.OpenMU.AttributeSystem.StatAttribute, BasicModel.StatAttribute>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.AttributeSystem.ConstValueAttribute, MUnique.OpenMU.AttributeSystem.ConstValueAttribute>()
            .Include<MUnique.OpenMU.AttributeSystem.ConstValueAttribute, BasicModel.ConstValueAttribute>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.AttributeSystem.AttributeRelationship, MUnique.OpenMU.AttributeSystem.AttributeRelationship>()
            .Include<MUnique.OpenMU.AttributeSystem.AttributeRelationship, BasicModel.AttributeRelationship>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.Interfaces.LetterHeader, MUnique.OpenMU.Interfaces.LetterHeader>()
            .Include<MUnique.OpenMU.Interfaces.LetterHeader, BasicModel.LetterHeader>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.Interfaces.Friend, MUnique.OpenMU.Interfaces.Friend>()
            .Include<MUnique.OpenMU.Interfaces.Friend, BasicModel.Friend>();

        Mapster.TypeAdapterConfig.GlobalSettings.NewConfig<MUnique.OpenMU.PlugIns.PlugInConfiguration, MUnique.OpenMU.PlugIns.PlugInConfiguration>()
            .Include<MUnique.OpenMU.PlugIns.PlugInConfiguration, BasicModel.PlugInConfiguration>();


        isConfigured = true;
    }
}
