// <copyright file="WCoinWallet.Generated.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by a roslyn code generator.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace MUnique.OpenMU.Persistence.BasicModel;

using MUnique.OpenMU.Persistence.Json;

/// <summary>
/// A plain implementation of <see cref="WCoinWallet"/>.
/// </summary>
public partial class WCoinWallet : MUnique.OpenMU.DataModel.Entities.WCoinWallet, IIdentifiable, IConvertibleTo<WCoinWallet>
{
    /// <inheritdoc />
    public WCoinWallet()
    {
    }

    /// <inheritdoc />
    public WCoinWallet(System.Guid id)
        : base(id)
    {
    }

    
    

    /// <inheritdoc/>
    public override bool Equals(object obj)
    {
        var baseObject = obj as IIdentifiable;
        if (baseObject != null)
        {
            return baseObject.Id == this.Id;
        }

        return base.Equals(obj);
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return this.Id.GetHashCode();
    }

    /// <inheritdoc/>
    public WCoinWallet Convert() => this;
}
